# Generated by Django 4.2 on 2023-04-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('discription', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('eg', 'eyeglass'), ('sg', 'sunglass'), ('kg', 'kidsglass'), ('cg', 'computerglass'), ('psg', 'power_sunglass'), ('cl', 'contact_lens')], max_length=200)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
