# Generated by Django 4.2 on 2023-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customer_state_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('kerala', 'kerala'), ('karnataka', 'karnataka'), ('tamilnadu', 'tamilnadu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('packed', 'packed'), ('on the way', 'on the way'), ('Delivered', 'Delivered'), ('cancel', 'cancel'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
